name: Docker images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  cargoverse:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: debian
            tags: |
              jasontheiler/cargoverse:latest
              jasontheiler/cargoverse:debian
              jasontheiler/cargoverse:debian-${{ github.run_id }}
          - name: alpine
            tags: |
              jasontheiler/cargoverse:alpine
              jasontheiler/cargoverse:alpine-${{ github.run_id }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:cargoverse"
          file: ./Dockerfile.${{ matrix.name }}
          platforms: |
            linux/amd64
            linux/arm64
          provenance: false
          push: true
          tags: ${{ matrix.tags }}
